# Generated by Django 3.1.4 on 2020-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('url',)},
        ),
        migrations.CreateModel(
            name='WebsiteAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status_code', models.SmallIntegerField()),
                ('timeout', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.website')),
            ],
        ),
    ]
