# Generated by Django 3.1.4 on 2020-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_auto_20201214_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteavailability',
            name='ip_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='websiteavailability',
            name='response_status_code',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='websiteavailability',
            name='server',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
