# Generated by Django 3.1.4 on 2020-12-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20201214_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ('id',)},
        ),
    ]
