# Generated by Django 3.1.4 on 2020-12-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20201215_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteavailability',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Website availabilities'},
        ),
    ]
